src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\ManyToMany;

#[ORM\Entity(repositoryClass: CarRepository::class)]
class Car
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $make = null;

    #[ORM\Column(length: 255)]
    private ?string $model = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $build_at = null;

    /**
     * @var Collection<int, Colour>
     */
    #[ManyToMany(targetEntity: Colour::class, inversedBy: 'cars')]
    #[JoinTable(name: 'car_colours')]
    private Collection $colours;

    public function __construct()
    {
        $this->colours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMake(): ?string
    {
        return $this->make;
    }

    public function setMake(string $make): static
    {
        $this->make = $make;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): static
    {
        $this->model = $model;

        return $this;
    }

    public function getBuildAt(): ?\DateTimeImmutable
    {
        return $this->build_at;
    }

    public function setBuildAt(\DateTimeImmutable $build_at): static
    {
        $this->build_at = $build_at;

        return $this;
    }

    /**
     * @return Collection<int, Colour>
     */
    public function getColours(): Collection
    {
        return $this->colours;
    }

    /**
     * @param Colour[] $colours
     * @return void
     */
    public function setColours(array $colours): void
    {
        $this->colours = new ArrayCollection($colours);
    }

}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\DTO\CarDTO;
use App\Entity\Car;
use App\Exceptions\CarNotFoundException;
use App\Facade\CarFacade;
use App\Repository\CarRepository;
use App\Request\CreateCarRequest;
use App\ResponseFactory\CarResponseFactory;
use JetBrains\PhpStorm\NoReturn;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/')]
class CarController extends AbstractController
{
    public function __construct(
        private CarRepository $carRepository,
        private CarResponseFactory $carResponseFactory,
        private CarFacade $carFacade
    ) {
    }

    #[Route('/cars', name: 'app_car_list', methods: ['GET'])]
    public function index(): Response
    {
        return new JsonResponse($this->carResponseFactory->fromEntitiesToCarResponse($this->carRepository->findAll()));
    }

    #[Route('/cars', name: 'app_car_new', methods: ['POST'])]
    public function new(CreateCarRequest $request): Response
    {
        try {
            $errors = $request->validate();
            if (count($errors)) {
                return new JsonResponse($errors, 400);
            }
            $carDto = new CarDto();
            $carDto->fillFromRequest($request);
            $carEntity = $this->carFacade->save($carDto);

        } catch (\Exception) {
            return new JsonResponse(['error' => 'Error occurred when saving car.'], 500);
        }
        return new JsonResponse($this->carResponseFactory->fromEntityToCarResponse($carEntity));
    }

    #[Route('/car/{carId}', name: 'app_car_show', methods: ['GET'])]
    public function show(?string $carId = null): Response
    {
        if ((int)$carId === 0) {
            return new JsonResponse(['error' => 'Not valid format of Id, use integer instead.'], 400);
        }
        $carEntity = $this->carRepository->find((int)$carId);
        if ($carEntity !== null) {
            return new JsonResponse($this->carResponseFactory->fromEntityToCarResponse($carEntity));
        }

        return new JsonResponse(['error' => 'Not found.'], 404);
    }

    #[Route('/cars/{carId}', name: 'app_car_delete', methods: ['DELETE'])]
    public function delete(?string $carId): Response
    {
        if ((int)$carId === 0) {
            return new JsonResponse(['error' => 'Not valid format of Id, use integer instead.'], 400);
        }

        try {
            $this->carFacade->remove((int)$carId);
        } catch (CarNotFoundException) {
            return new JsonResponse(['error' => 'Id was not found.'], 404);
        }

        return new JsonResponse(['message' => 'Removed.'], 200);
    }

}

templates/car/_delete_form.html.twig
<form method="post" action="{{ path('app_car_delete', {'id': car.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ car.id) }}">
    <button class="btn">Delete</button>
</form>

templates/car/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/car/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Car{% endblock %}

{% block body %}
    <h1>Edit Car</h1>

    {{ include('car/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_car_index') }}">back to list</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}

templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car index{% endblock %}

{% block body %}
    <h1>Car index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Make</th>
                <th>Model</th>
                <th>Build_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for car in cars %}
            <tr>
                <td>{{ car.id }}</td>
                <td>{{ car.make }}</td>
                <td>{{ car.model }}</td>
                <td>{{ car.buildAt ? car.buildAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_car_show', {'id': car.id}) }}">show</a>
                    <a href="{{ path('app_car_edit', {'id': car.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_car_new') }}">Create new</a>
{% endblock %}

templates/car/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Car{% endblock %}

{% block body %}
    <h1>Create new Car</h1>

    {{ include('car/_form.html.twig') }}

    <a href="{{ path('app_car_index') }}">back to list</a>
{% endblock %}

templates/car/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Car{% endblock %}

{% block body %}
    <h1>Car</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ car.id }}</td>
            </tr>
            <tr>
                <th>Make</th>
                <td>{{ car.make }}</td>
            </tr>
            <tr>
                <th>Model</th>
                <td>{{ car.model }}</td>
            </tr>
            <tr>
                <th>Build_at</th>
                <td>{{ car.buildAt ? car.buildAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_car_index') }}">back to list</a>

    <a href="{{ path('app_car_edit', {'id': car.id}) }}">edit</a>

    {{ include('car/_delete_form.html.twig') }}
{% endblock %}